//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RIB.Training.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class BAS_TODOITEM
    {
        public int ID { get; set; }
        public int SORTING { get; set; }
        public string DESCRIPTION { get; set; }
        public bool ISDEFAULT { get; set; }
        public System.DateTime CREATEDDATE { get; set; }
        public Nullable<System.DateTime> UPDATEDDATE { get; set; }
        public int VERSION { get; set; }
    }
}
